### ISSUE TITLE
EEBUS (Elli Charger Pro): SIGSEGV in V0.110.0 during startup

### ISSUE THREAD

**Issue by joslippert** [DerAndereAndi/evcc#1]
### Describe the bug

Since version 0.110.0, a SIGSEGV occurs at startup with EEBUS (Elli Charger Pro).
The previous versions worked perfectly.

### Steps to reproduce

1. evcc  -l trace charger

### Configuration details

```yaml
chargers:
- type: template
  template: ellipro
  ski: mySKI
  ip: 192.168.178.41  
  name: Elli-Wallbox

vehicles:
- name: EV1
  type: template
  template: etron
  title: Audi_e-tron
  user: myEmail
  password: myPWD
  vin: myWAU
  capacity: 86  # KWH
```

### Log details

```text
evcc  -l trace charger

[main  ] INFO 2022/12/21 10:25:46 evcc 0.110.0
[main  ] INFO 2022/12/21 10:25:46 using config file: /home/oracle/evcc/evcc.yaml
[db    ] INFO 2022/12/21 10:25:46 using sqlite database: /home/oracle/.evcc/evcc.db
[db    ] TRACE 2022/12/21 10:25:46 SELECT count(*) FROM sqlite_master WHERE type='table' AND name="settings" -1 <nil>
[db    ] TRACE 2022/12/21 10:25:46 SELECT sql FROM sqlite_master WHERE type IN ("table","index") AND tbl_name = "settings" AND sql IS NOT NULL order by type = "table" desc 1 <nil>
[db    ] TRACE 2022/12/21 10:25:46 SELECT * FROM `settings` LIMIT 1 -1 <nil>
[db    ] TRACE 2022/12/21 10:25:46 SELECT * FROM `settings` 6 <nil>
[eebus ] INFO 2022/12/21 10:25:46 Local SKI:  4a3846aadbbfb032f74c26055277584bee7809e6
[eebus ] TRACE 2022/12/21 10:25:46 registering ski: mySKI
[eebus ] DEBUG 2022/12/21 10:25:46 mdns: start search
[eebus ] DEBUG 2022/12/21 10:25:46 mdns: announce
[eebus ] DEBUG 2022/12/21 10:25:46 mdns: using avahi
[eebus ] DEBUG 2022/12/21 10:25:46 starting websocket server on :4712
[eebus ] DEBUG 2022/12/21 10:25:46 ski: mySKI name: Elli-Wallbox-2051A14979 brand: Elli model: Wallbox typ: Wallbox identifier: Elli-Wallbox-2051A14979 register: false
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0xf6c334]

goroutine 23 [running]:
github.com/enbility/eebus-go/service.(*mdns).resolveEntries(0xc000e9fc20)
	/home/runner/go/pkg/mod/github.com/enbility/eebus-go@v0.1.5/service/mdns.go:329 +0x1f4
created by github.com/enbility/eebus-go/service.(*mdns).RegisterMdnsSearch
	/home/runner/go/pkg/mod/github.com/enbility/eebus-go@v0.1.5/service/mdns.go:273 +0x265
```

### What type of operating system are you running?

Linux

### Version

evcc version 0.110.0
